services:
  - type: web
    name: vedas-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: VEDAS_API_KEY
        sync: false
      - key: VEDAS_BASE_URL
        value: https://vedas.sac.gov.in/vconsole

  - type: static
    name: vedas-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
